services:
  liturgy-api:
    image: liturgy-api:latest
    build: https://github.com/Liturgical-Calendar/LiturgicalCalendarAPI.git#development
    restart: unless-stopped
    ports:
      - ${STORYBOOK_API_PORT:-8000}:8000 # You may change the port that the API is exposed on, i.e. 8092:8000
  storybook:
    image: liturgy-components-js:latest
    build: https://github.com/Liturgical-Calendar/liturgy-components-js.git#main
    ports:
      - ${STORYBOOK_PORT:-6006}:6006
    ## If you would like to continue local development of the storybook, then you must run the docker-compose in the same folder as the project repository,
    ##   and uncomment all of the following lines for volume mounts
    #volumes:
    #  - ./dist:/app/dist
    #  - ./src:/app/src
    #  - ./.storybook:/app/.storybook
    ## Also if you customize the STORYBOOK_API_PORT port in a .env file, then you must mount the .env file in the container:
    #  - ./.env:/app/.env
    ##  otherwise storybook will not pick up on the STORYBOOK_API_PORT environment variable
    restart: unless-stopped
    depends_on:
      - liturgy-api
