services:
  liturgy-api:
    image: liturgy-api:latest
    #build: https://github.com/Liturgical-Calendar/LiturgicalCalendarAPI.git#development
    restart: unless-stopped
    ports:
      - 8000:8000
  storybook:
    image: liturgy-components-js:latest
    #build: https://github.com/Liturgical-Calendar/liturgy-components-js.git#main
    ports:
      - 6006:6006
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src
      - ./.storybook:/app/.storybook
    environment:
      STORYBOOK_API_PORT: 8000
    restart: unless-stopped
    depends_on:
      - liturgy-api
